--------------------------------------------------------------------------------
-- Copyright (c) 1995-2013 Xilinx, Inc.  All rights reserved.
--------------------------------------------------------------------------------
--   ____  ____
--  /   /\/   /
-- /___/  \  /    Vendor: Xilinx
-- \   \   \/     Version: P.20131013
--  \   \         Application: netgen
--  /   /         Filename: .vhd
-- /___/   /\     Timestamp: Thu Dec 08 15:10:46 2016
-- \   \  /  \ 
--  \___\/\___\
--             
-- Command	: -intstyle ise -ar Structure -tm TopModule -w -dir netgen/synthesis -ofmt vhdl -sim TopModule.ngc TopModule_synthesis.vhd 
-- Device	: xc7a100t-3-csg324
-- Input file	: TopModule.ngc
-- Output file	: C:\Users\Varun Sharma\Documents\GitHub\AHD-Project-2016\VHDL Code\RC5\netgen\synthesis\TopModule_synthesis.vhd
-- # of Entities	: 1
-- Design Name	: TopModule
-- Xilinx	: C:\Xilinx\14.7\ISE_DS\ISE\
--             
-- Purpose:    
--     This VHDL netlist is a verification model and uses simulation 
--     primitives which may not represent the true implementation of the 
--     device, however the netlist is functionally correct and should not 
--     be modified. This file cannot be synthesized and should only be used 
--     with supported simulation tools.
--             
-- Reference:  
--     Command Line Tools User Guide, Chapter 23
--     Synthesis and Simulation Design Guide, Chapter 6
--             
--------------------------------------------------------------------------------

